version: '3'
services:
  db:
    image: postgres
    restart: always
    network_mode: bridge
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ch4ng3
      POSTGRES_USER: ch4ng3
      POSTGRES_PASSWORD: ch4ng3

  api:
    image: ch4ng3-api
    restart: always
    network_mode: bridge
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://ch4ng3:ch4ng3@db:5432/ch4ng3?sslmode=disable
      - PREFIX=/api
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    command: bash -c "bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    links:
      - db

