version: '3'
services:
  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=very_str0ng_P@ssw0rd
  web:
    image: "bank:latest"
    ports:
     - "7777:80"
    depends_on: 
     - mysql