# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEoQIBAAKCAQEA0om/USMvnddk+OAMZWSUExloEmWFJhHcpyTcg/9Lr0rwNl/f
    yFcRnR6OT5/gciAbHPp4YOHWMckvetHCLsQ03jmkPM3r8AgSFMYC5FMZs72LP6w2
    PI1Yh0w4L/hCmW35W6kySQonfaIKMkByg2kETXcWE5bjdg90W+nGcIOCet+oADJX
    mBO+sELhx5A/3ynAcwKObv0fNlrOxdqPlePqMqwCJnTOxmOj0Hagn5muXa6PHo+8
    oaR0mTWg8leULinFDKHJePi/EAZMcFgrtMzv8KsgGMARQtuNxBRA+y/BpbF5pOhA
    S7ry+WPjEV3zvYZ6ow2UzSyiLi79MW5iyjtmhwIDAQABAoH/HZtBTCemiou/pz/a
    fmemawknmW6tSq04WkjUubss6XmgTgUtcv7Le0zQtmHFLkdViL2wL++SL24bPypA
    JFNzG8z/S42poBeCc2lk/raw5pXA/zM4bUtzJ5OQUy6WLv1IE5u3do32/7PJu0dU
    0yXxdPNKJ3cQhYmm00YMocXck2qesUVqT+lBTR/iqYcvfbZ81ETRsFJ7rCX7gB43
    yqLE20blzkUALuQJxatYwmzPmRG6Zn9Y389MA+EAmv5owpPsf4r38FXyfDizwmWE
    xUwpfIcKsIyFCCby+rPa/GCxOF4DU+qEHxDHZu5VcaM1rnP7wJFYJegkH0oD6rrd
    xlbhAoGBAPwVgnv3IfcdDMQ/JudcgqTZqIKzR4n2ht55pqhZ1yUaXucDivJMSf4V
    nRwf4H951BvRekO2cyQZdSDZ0/XpeFgCsPNz6J49s1Gvx7nZqhF3SLLv8mB+tHoh
    LuS++fJBUUs0c0d/PWPk//fnhX9Wu7RvhH0OwA9jrHLE7f5D9eIzAoGBANXPBGzQ
    ZqKCSh8MlRhf0e0T+P3QCbG7VmSSmXYZiMi0a0xTgJIlidnnmKwdynXWe6/2JX1i
    9zVMuUPDNUqvc6x/gtm0rWIYPFA4wD7jjgOQ7OSBDDO/YBnQChdW/zXOnoXw9hT6
    IdLdkHa4RZWwTShMD4RuaoRcyKyDpX1hQN5dAoGACQQb7qMgK952Hm7DzXKZmZvP
    Ux1maaDPohVnyI2uDD2tN0YBKjlgTB4pyF+7f9OzqmsLnHBiHeBrOAmSczEuhLdT
    7OEwaLh8OWe4FQWb95P0nbHHUXw2qEeXjcbm2atMZQwzM1NxtqjyHsPBGpTXkdSL
    QI3OgL5n5JL2kCmOGdECgYB5f6yqETthudxZDJNlSH5I1QK3aRM5NpX/jPc8D4KV
    W0FmHEWBx2cwttUhacR1di7PbXcca7LDTRgyk6mjCVUYf1ViVbP5fIA5riZBFprL
    F/4mU9cVSPlZcclqPfvFHecjgiy0+vdhlprTfB++0nLmJWLkBMLu+LLopd7TAwMT
    2QKBgQDrJWegoZ509fJ/YMS0lTibyNqIn7+S/tQ5myTfuMmBEGlsCljq4kK+UwnQ
    68JSSSXX7NaLuK8mRdoq1uGtNJVJo/7S2f0r77+U2NCRpdJjaBM9natd/SYZyJJC
    Fs29Oajffaf/hxhfZp20RgD8MkNuRtw9mhC48YmZkKdoRdM4TQ==
    -----END RSA PRIVATE KEY-----
  public_key_base: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0om/USMvnddk+OAMZWSU
    ExloEmWFJhHcpyTcg/9Lr0rwNl/fyFcRnR6OT5/gciAbHPp4YOHWMckvetHCLsQ0
    3jmkPM3r8AgSFMYC5FMZs72LP6w2PI1Yh0w4L/hCmW35W6kySQonfaIKMkByg2kE
    TXcWE5bjdg90W+nGcIOCet+oADJXmBO+sELhx5A/3ynAcwKObv0fNlrOxdqPlePq
    MqwCJnTOxmOj0Hagn5muXa6PHo+8oaR0mTWg8leULinFDKHJePi/EAZMcFgrtMzv
    8KsgGMARQtuNxBRA+y/BpbF5pOhAS7ry+WPjEV3zvYZ6ow2UzSyiLi79MW5iyjtm
    hwIDAQAB
    -----END PUBLIC KEY-----

production:
  secret_key_base: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEoQIBAAKCAQEA0om/USMvnddk+OAMZWSUExloEmWFJhHcpyTcg/9Lr0rwNl/f
    yFcRnR6OT5/gciAbHPp4YOHWMckvetHCLsQ03jmkPM3r8AgSFMYC5FMZs72LP6w2
    PI1Yh0w4L/hCmW35W6kySQonfaIKMkByg2kETXcWE5bjdg90W+nGcIOCet+oADJX
    mBO+sELhx5A/3ynAcwKObv0fNlrOxdqPlePqMqwCJnTOxmOj0Hagn5muXa6PHo+8
    oaR0mTWg8leULinFDKHJePi/EAZMcFgrtMzv8KsgGMARQtuNxBRA+y/BpbF5pOhA
    S7ry+WPjEV3zvYZ6ow2UzSyiLi79MW5iyjtmhwIDAQABAoH/HZtBTCemiou/pz/a
    fmemawknmW6tSq04WkjUubss6XmgTgUtcv7Le0zQtmHFLkdViL2wL++SL24bPypA
    JFNzG8z/S42poBeCc2lk/raw5pXA/zM4bUtzJ5OQUy6WLv1IE5u3do32/7PJu0dU
    0yXxdPNKJ3cQhYmm00YMocXck2qesUVqT+lBTR/iqYcvfbZ81ETRsFJ7rCX7gB43
    yqLE20blzkUALuQJxatYwmzPmRG6Zn9Y389MA+EAmv5owpPsf4r38FXyfDizwmWE
    xUwpfIcKsIyFCCby+rPa/GCxOF4DU+qEHxDHZu5VcaM1rnP7wJFYJegkH0oD6rrd
    xlbhAoGBAPwVgnv3IfcdDMQ/JudcgqTZqIKzR4n2ht55pqhZ1yUaXucDivJMSf4V
    nRwf4H951BvRekO2cyQZdSDZ0/XpeFgCsPNz6J49s1Gvx7nZqhF3SLLv8mB+tHoh
    LuS++fJBUUs0c0d/PWPk//fnhX9Wu7RvhH0OwA9jrHLE7f5D9eIzAoGBANXPBGzQ
    ZqKCSh8MlRhf0e0T+P3QCbG7VmSSmXYZiMi0a0xTgJIlidnnmKwdynXWe6/2JX1i
    9zVMuUPDNUqvc6x/gtm0rWIYPFA4wD7jjgOQ7OSBDDO/YBnQChdW/zXOnoXw9hT6
    IdLdkHa4RZWwTShMD4RuaoRcyKyDpX1hQN5dAoGACQQb7qMgK952Hm7DzXKZmZvP
    Ux1maaDPohVnyI2uDD2tN0YBKjlgTB4pyF+7f9OzqmsLnHBiHeBrOAmSczEuhLdT
    7OEwaLh8OWe4FQWb95P0nbHHUXw2qEeXjcbm2atMZQwzM1NxtqjyHsPBGpTXkdSL
    QI3OgL5n5JL2kCmOGdECgYB5f6yqETthudxZDJNlSH5I1QK3aRM5NpX/jPc8D4KV
    W0FmHEWBx2cwttUhacR1di7PbXcca7LDTRgyk6mjCVUYf1ViVbP5fIA5riZBFprL
    F/4mU9cVSPlZcclqPfvFHecjgiy0+vdhlprTfB++0nLmJWLkBMLu+LLopd7TAwMT
    2QKBgQDrJWegoZ509fJ/YMS0lTibyNqIn7+S/tQ5myTfuMmBEGlsCljq4kK+UwnQ
    68JSSSXX7NaLuK8mRdoq1uGtNJVJo/7S2f0r77+U2NCRpdJjaBM9natd/SYZyJJC
    Fs29Oajffaf/hxhfZp20RgD8MkNuRtw9mhC48YmZkKdoRdM4TQ==
    -----END RSA PRIVATE KEY-----
  public_key_base: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0om/USMvnddk+OAMZWSU
    ExloEmWFJhHcpyTcg/9Lr0rwNl/fyFcRnR6OT5/gciAbHPp4YOHWMckvetHCLsQ0
    3jmkPM3r8AgSFMYC5FMZs72LP6w2PI1Yh0w4L/hCmW35W6kySQonfaIKMkByg2kE
    TXcWE5bjdg90W+nGcIOCet+oADJXmBO+sELhx5A/3ynAcwKObv0fNlrOxdqPlePq
    MqwCJnTOxmOj0Hagn5muXa6PHo+8oaR0mTWg8leULinFDKHJePi/EAZMcFgrtMzv
    8KsgGMARQtuNxBRA+y/BpbF5pOhAS7ry+WPjEV3zvYZ6ow2UzSyiLi79MW5iyjtm
    hwIDAQAB
    -----END PUBLIC KEY-----
